Script started on Wed 16 Sep 2015 05:40:12 PM EDT
[?1034hbash-4.1$ cd ~/os161/root
bash-4.1$ sys161 kernel
sys161: System/161 release 1.14, compiled Sep  4 2014 10:34:58

OS/161 base system version 1.11
Copyright (c) 2000, 2001, 2002, 2003
   President and Fellows of Harvard College.  All rights reserved.

Put-your-group-name-here's system version 0 (ASST0 #1)

Cpu is MIPS r2000/r3000
336k physical memory available
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
hardclock on ltimer0 (100 hz)
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lhd0 at lamebus0
lhd1 at lamebus0
lser0 at lamebus0
con0 at lser0
pseudorand0 (virtual)

OS/161 kernel [? for menu]: p /sbin/poe weroff <return>
Operation took 0.000159280 seconds
OS/161 kernel [? for menu]: Shutting down.
The system is halted.
sys161: 826627820 cycles (7558629k, 18u, 819069173i)
sys161: 3977 irqs 6 exns 0r/0w disk 28r/704w console 8r/0w/3m emufs 0r/0w net
sys161: Elapsed real time: 32.611156 seconds (25.348 mhz)
sys161: Elapsed virtual time: 33.065112800 seconds (25 mhz)
bash-4.1$ exit
exit

Script done on Wed 16 Sep 2015 05:41:52 PM EDT
